name: dkube-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip
  - pip:
    - /tmp/dkube_cicd_controller-1.6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl 
    - git+https://github.com/oneconvergence/dkube.git@3.8
    - matplotlib
    - logger
    - scipy
    - mlflow
    - argparse
    - kfp-server-api==1.2.0
    - kfp==1.6.3
variables:
  DKUBE_USER_ACCESS_TOKEN: ""
